### PR TITLE
Python3.6 support + "Client Random" + "br" decompression support

### PR DESCRIPTION
**Pull request by LetMeR00t**
- Add Python3.6 support (Python2.7 doesn't work anymore due to mitmproxy)
- Add a new tls_master regex to client "Client Random"
- Add the "br" decompression support

Fix issue for https://github.com/hatching/httpreplay/issues/19 and https://github.com/hatching/httpreplay/issues/23

Tested with both pytest versions, all tests passed (except one, but already in xfail state)

### CODE REVIEW

**Comment by blshkv** [comment]
"All checks have failed" ?

**Comment by LetMeR00t** [comment]
@blshkv , if you check the details, you will see that pip2 is trying to recover mitmproxy 4.0.4 which doesn't exist ...
You have to install it using pip3

**Comment by LetMeR00t** [comment]
@jbremer @RicoVZ FYA

**Comment by blshkv** [comment]
The error basically means that you have to drop python2 because mitmproxy no longer supports it

**Comment by LetMeR00t** [comment]
@blshkv , well I agree with you but once you installed mitmproxy using pip3 and then compile the source code using python2, you have no issue to use mitmproxy in 4.0.4 as all tests passed (and in the code, you can see that i'm using the mitmproxy 4.0.4 source code which is well interpreted in python2)

**Comment by LetMeR00t** [comment]
Hi @blshkv, @jbremer , @RicoVZ 
Sorry for the last commits, I never used these tests before but it's very good when you understand how it works :)
Now the patch is okay, only python3.6 in the tests, see if we need to keep Python2.7 ?
Regards

**Comment by blshkv** [comment]
Python2 will be out of support next year, so don't waster your time. You can create a new branch if you really want a smooth transition but i would not care

**Comment by LetMeR00t** [comment]
After reviewing my code again, I think I will need some more changes before you can review officially, I will do this asap. (Code is working but results of functions are returning bytes when they could return strings ...)

**Comment by LetMeR00t** [comment]
My repository was updated with your's today.

**Pull request closed without merging**
