### PR TITLE
Add and use SSLKEYLOGFILE information from mitmproxy 

### PR DESCRIPTION
**Pull request by LetMeR00t**
This code doesn't work yet but it's only for sharing the new additions

### CODE REVIEW

**Comment by jbremer** [comment]
@LetMeR00t I don't remember what your status on this was, I believe you got something working? Could you please update me / update the PRs / etc? Thanks!

**Comment by LetMeR00t** [comment]
Hi @jbremer,
Indeed, the code is working respecting my comments concerning Cuckoo here : https://github.com/cuckoosandbox/cuckoo/pull/2104
It seems that everything using GCM will not work...
Could you try on your own ? 
You will probably need this part : https://github.com/cuckoosandbox/cuckoo/pull/2102/commits/3c39049127c48c2d0a98e7c6840a98b3445d5169 (Line 71 to 75) to allow mitmproxy to use the MITMPROXY_SSLKEYLOGFILE variable.

**Comment by LetMeR00t** [comment]
Sorry, I have to modify my meanings...
You will need this PR on Cuckoo : https://github.com/cuckoosandbox/cuckoo/pull/2104/files

With the previous PR and this one, you should be able (respecting my previous comments) to be able to decipher the traffic using mitmproxy in transparent mode.
On my way, it's working perfectly as expected.
Don't hesitate if you need more information

**Comment by LetMeR00t** [comment]
Hi @jbremer,
Keep updated this also for the fix issue on Cuckoo.
If you think I misunderstanding something, tell me.
Thank you

**Comment by LetMeR00t** [comment]
Duplicate : https://github.com/hatching/httpreplay/pull/25

**Pull request closed without merging**
